
version: "3.6"
services:
  jackett:
    container_name: "jackett"
    hostname: jackett
    image: linuxserver/jackett:latest
    networks:
      - "media_default"
    ports:
      - "9117:9117/tcp"
    restart: "unless-stopped"
    volumes:
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Configs/Jackett:/config"
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Torrents:/downloads"
  radarr:
    container_name: "radarr"
    hostname: "radarr"
    image: linuxserver/radarr:latest
    networks:
      - "media_default"
    ports:
      - "7878:7878/tcp"
    restart: "unless-stopped"
    volumes:
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Configs/Radarr:/config"
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Torrents:/downloads"
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Movies:/movies"
  sonarr:
    container_name: "sonarr"
    hostname: "sonarr"
    image: linuxserver/sonarr:latest
    networks:
      - "media_default"
    ports:
      - "8989:8989/tcp"
    restart: "unless-stopped"
    volumes:
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/TV:/tv"
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Configs/Sonarr:/config"
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Torrents:/downloads"  
  ombi:
    container_name: ombi
    hostname: ombi
    image: linuxserver/ombi:latest
    networks:
    - "media_default"
    ports:
      - 3579:3579
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Configs/Ombi:/config
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    networks:
      - "media_default"
    ports:
      - 8081:80
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Configs/Organizr:/config

  emby:
    container_name: embyserver
    hostname: emby
    image: emby/embyserver:latest
    networks:
      - "media_default"
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: on-failure
    volumes:
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Configs/emby:/config"
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/TV:/tv"
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Movies:/movies"
  qbittorrent:
    container_name: qbittorrent
    hostname: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent:latest
    networks:
      - "media_default"
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "8080:8080/tcp"
    restart: "unless-stopped"
    volumes:
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Configs/QBittorrent:/config"
      - "/srv/dev-disk-by-uuid-d03ef333-59df-45f4-9551-01527bbc914a/Torrents:/downloads"      
networks:
  media_default:
    name: "media_default"