version: "3.6"
services:
  jackett:
    container_name: "jackett"
    hostname: jackett
    image: linuxserver/jackett:latest
    networks:
      - "media_default"
    ports:
      - "9117:9117/tcp"
    restart: "unless-stopped"
    volumes:
      - ${UUID_CONFIG_JACKET}
      - ${UUID_TORRENT}
  radarr:
    container_name: "radarr"
    hostname: "radarr"
    image: linuxserver/radarr:latest
    networks:
      - "media_default"
    ports:
      - "7878:7878/tcp"
    restart: "unless-stopped"
    volumes:
      - ${UUID_CONFIG_RADARR}
      - ${UUID_TORRENT}
      - ${UUID_MOV}
  sonarr:
    container_name: "sonarr"
    hostname: "sonarr"
    image: linuxserver/sonarr:latest
    networks:
      - "media_default"
    ports:
      - "8989:8989/tcp"
    restart: "unless-stopped"
    volumes:
      - ${UUID_TV}
      - ${UUID_CONFIG_SONARR}
      - ${UUID_TORRENT}  
  ombi:
    container_name: ombi
    hostname: ombi
    image: linuxserver/ombi:latest
    networks:
    - "media_default"
    ports:
      - 3579:3579
    restart: unless-stopped
    volumes:
      - ${UUID_CONFIG_OMBI}
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    networks:
      - "media_default"
    ports:
      - 8081:80
    restart: unless-stopped
    volumes:
      - ${UUID_CONFIG_ORAGANIZR}

  emby:
    container_name: embyserver
    hostname: emby
    image: emby/embyserver:latest
    networks:
      - "media_default"
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: on-failure
    volumes:
      - ${UUID_CONFIG_EMBY}
      - ${UUID_TV}
      - ${UUID_MOV}
  qbittorrent:
    container_name: qbittorrent
    hostname: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    networks:
      - "media_default"
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "8080:8080/tcp"
    restart: "unless-stopped"
    volumes:
      - ${UUID_CONFIG_QBITORRENT}
      - ${UUID_TORRENT}     
networks:
  media_default:
    name: "media_default"
