services:       

# ██████╗ ██████╗  ██████╗ ██╗    ██╗██╗      █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔═══██╗██║    ██║██║     ██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝██████╔╝██║   ██║██║ █╗ ██║██║     ███████║██████╔╝██████╔╝
# ██╔═══╝ ██╔══██╗██║   ██║██║███╗██║██║     ██╔══██║██╔══██╗██╔══██╗
# ██║     ██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║██║  ██║██║  ██║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═
                            
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    platform: linux/amd64
    environment: 
      - ${PUID}
      - ${PGID}
      - ${TZ}
    volumes:
      - ${ARRPATH}Prowlarr/config:/config
      - ${ARRPATH}Prowlarr/backup:/data/Backup
      - ${ARRPATH}Downloads:/downloads
    ports:
      - 9696:9696
    restart: unless-stopped
    healthcheck:
      test: curl -f http://prowlarr:9696/ping || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

# ███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
# ███████╗██║   ██║██╔██╗ ██║███████║██████╔╝██████╔╝
# ╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗██╔══██╗
# ███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║██║  ██║
# ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                                 
      
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    platform: linux/amd64
    environment: 
      - ${PUID}
      - ${PGID}
      - ${TZ}
    volumes:
      - ${ARRPATH}Sonarr/config:/config
      - ${ARRPATH}Sonarr/backup:/data/Backup
      - ${ARRPATH}Sonarr/tvshows:/data/tvshows
      - ${ARRPATH}Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    healthcheck:
      test: curl -f http://sonarr:8989/ping || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
      
# ██████╗  █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                              

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    platform: linux/amd64
    environment: 
      - ${PUID}
      - ${PGID}
      - ${TZ}
    volumes:
      - ${ARRPATH}Radarr/config:/config
      - ${ARRPATH}Radarr/movies:/data/movies
      - ${ARRPATH}Radarr/backup:/data/Backup
      - ${ARRPATH}Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    healthcheck:
      test: curl -f http://radarr:7878/ping || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

#      ██╗███████╗██╗     ██╗  ██╗   ██╗███████╗██╗███╗   ██╗
#      ██║██╔════╝██║     ██║  ╚██╗ ██╔╝██╔════╝██║████╗  ██║
#      ██║█████╗  ██║     ██║   ╚████╔╝ █████╗  ██║██╔██╗ ██║
# ██   ██║██╔══╝  ██║     ██║    ╚██╔╝  ██╔══╝  ██║██║╚██╗██║
# ╚█████╔╝███████╗███████╗███████╗██║   ██║     ██║██║ ╚████║
#  ╚════╝ ╚══════╝╚══════╝╚══════╝╚═╝   ╚═╝     ╚═╝╚═╝  ╚═══╝

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    platform: linux/amd64
    environment: 
      - ${PUID}
      - ${PGID}
      - ${TZ}
    ports:
      - '8096:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    volumes:
      - ${ARRPATH}Jellyfin/config:/config
      - ${ARRPATH}Radarr/movies:/data/Movies
      - ${ARRPATH}Sonarr/tvshows:/data/TVShows
    restart: unless-stopped
    healthcheck:
      test: curl -f http://jellyfin:8096/health || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
          
#  ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
# ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
# ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║   
# ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║   
# ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║   
#  ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝                                                                                          

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    platform: linux/amd64
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${ARRPATH}qbittorrent/config:/config
      - ${ARRPATH}Downloads:/downloads
      - ${ARRPATH}Radarr/movies:/data/Movies
      - ${ARRPATH}Sonarr/tvshows:/data/TVShows
    ports:
      - 8085:8085
      - 6881:6881
    environment: 
      - ${PUID}
      - ${PGID}
      - ${TZ}
      - WEBUI_PORT=8085
      - TORRENTING_PORT=6881
    healthcheck:
      test: ["CMD", "curl", "-f", "http://qbittorrent:8085"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s



#██████╗  █████╗ ███████╗ █████╗ ██████╗ ██████╗ 
#██╔══██╗██╔══██╗╚══███╔╝██╔══██╗██╔══██╗██╔══██╗
#██████╔╝███████║  ███╔╝ ███████║██████╔╝██████╔╝
#██╔══██╗██╔══██║ ███╔╝  ██╔══██║██╔══██╗██╔══██╗
#██████╔╝██║  ██║███████╗██║  ██║██║  ██║██║  ██║
#╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    platform: linux/amd64
    environment: 
      - ${PUID}
      - ${PGID}
      - ${TZ}
    ports:
    - 6767:6767
    volumes:
      - ${ARRPATH}bazarr/config:/config
      - ${ARRPATH}Radarr/movies:/data/Movies
      - ${ARRPATH}Sonarr/tvshows:/data/TVShows
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://bazarr:6767"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s


  qui:
    image: ghcr.io/autobrr/qui:latest
    container_name: qui
    hostname: qui
    environment: 
      - ${PUID}
      - ${PGID}
      - ${TZ}
    ports:
      - '7476:7476'
    volumes:
      - ${ARRPATH}qbittorrent/config:/config
      - ${ARRPATH}Downloads:/downloads
