version: "3.6"
services:
  jackett:
    container_name: "jackett"
    hostname: jackett
    image: linuxserver/jackett:latest
    networks:
      - "media_default"
    ports:
      - "9117:9117/tcp"
    restart: "unless-stopped"
    volumes:
      - $DOCKERDIR/Configs/Jackett:/config
      - $DOCKERDIR/Torrents:/downloads
  radarr:
    container_name: "radarr"
    hostname: "radarr"
    image: linuxserver/radarr:latest
    environment:
      - PUID=0
      - PGID=0
    networks:
      - "media_default"
    ports:
      - "7878:7878/tcp"
    restart: "unless-stopped"
    volumes:
      - $DOCKERDIR/Configs/Radarr:/config
      - $DOCKERDIR/downloads:/downloads
      - $DOCKERDIR/Movies:/movies
  sonarr:
    container_name: "sonarr"
    hostname: "sonarr"
    image: linuxserver/sonarr:latest
    environment:
      - PUID=0
      - PGID=0
    networks:
      - "media_default"
    ports:
      - "8989:8989/tcp"
    restart: "unless-stopped"
    volumes:
      - $DOCKERDIR/TV:/tv
      - $DOCKERDIR/Configs/Sonarr:/config
      - $DOCKERDIR/downloads:/downloads
  ombi:
    container_name: ombi
    hostname: ombi
    image: linuxserver/ombi:latest
    networks:
    - "media_default"
    ports:
      - 3579:3579
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/Configs/Ombi:/config

  qbittorrent:
    container_name: qbittorrent
    hostname: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    environment:
      - PUID=0
      - PGID=0
    networks:
      - "media_default"
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "8080:8080/tcp"
    restart: "unless-stopped"
    volumes:
      - $DOCKERDIR/Configs/QBittorrent:/config
      - $DOCKERDIR/downloads/complete:/downloads/complete

  emby:
    container_name: embyserver
    hostname: emby
    image: emby/embyserver:latest
    networks:
      - "media_default"
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: on-failure
    volumes:
      - $DOCKERDIR/Configs/emby:/config
      - $DOCKERDIR/TV:/tv
      - $DOCKERDIR/Movies:/movies

networks:
  media_default:
    name: "media_default"
